// Generated by CoffeeScript 1.4.0
(function() {
	var app, express, hbs, session;

	express = require('express');

	hbs = require('hbs');

	session = require('cookie-session');

	app = express();

	app.set('view engine', 'html');

	app.engine('html', hbs.__express);

	app.use(session({
		secret: 'todotopsecret'
	}));

	app.get('/todo', function(req, res) {
		return res.render('example');
	});

	app.use("/javascripts", express["static"](__dirname + "/javascripts"));

	app.use(function(req, res, next) {
		res.redirect('/todo');
		return next();
	}).listen(8080);

}).call(this);
