// Generated by CoffeeScript 1.8.0
(function() {
  var http, nodestatic, server, web;

  http = require('http');

  nodestatic = require('node-static');

  web = new nodestatic.Server('./javascripts');

  server = http.createServer(function(request, response) {
    return request.addListener('end', function() {
      return web.serve(request, response);
    }).resume();
  });

  server.listen(8081);

}).call(this);
