version: "2"
services:
  front:
     image: nginx
     ports:
         - "80:80"
     links:
         - "php-fpm"
     volumes:
         - "/var/www:/var/www:ro"
         - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  php-fpm:
     image: php:lastest
     volumes:
         - "/var/www:/var/www:rw"
